-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- proxy
-- vim.env.http_proxy = "http://127.0.0.1:7890"
-- vim.env.https_proxy = "http://127.0.0.1:7890"
-- vim.env.ALL_PROXY = "socks5://127.0.0.1:7891"
