-- return {
--     'nvim-telescope/telescope.nvim', tag = 'v0.2.0',
--       dependencies = {
--         { 'nvim-lua/plenary.nvim' },
--         { 'BurntSushi/ripgrep' },
--         { 'nvim-telescope/telescope-fzf-native.nvim' },
--         { 'sharkdp/fd' },
--       },
--     }

-- ~/.config/nvim/lua/plugins/telescope.lua
return {
	-- 'nvim-telescope/telescope.nvim',
	-- tag = 'v0.2.0',                       -- 稳定版
	-- dependencies = {
	--   { 'nvim-lua/plenary.nvim' },           -- 必需
	--   { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' }, -- 可选，加速排序
	--   { 'BurntSushi/ripgrep' },
	--   { 'sharkdp/fd' },
	-- },
	-- keys = {
	--   { '<leader>sf', '<cmd>Telescope find_files<cr>',  desc = 'Find Files' },
	--   { '<leader>sg', '<cmd>Telescope live_grep<cr>',   desc = 'Live Grep' },
	--   { '<leader>sb', '<cmd>Telescope buffers<cr>',     desc = 'Buffers' },
	--   { '<leader>sh', '<cmd>Telescope help_tags<cr>',   desc = 'Help' },
	-- },
	-- config = function()
	--   require('telescope').setup{
	--     defaults = {
	--       prompt_prefix = '🔍 ',
	--       selection_caret = '➤ ',
	--       initial_mode = 'insert',
	--       path_display = { 'truncate' },               -- 长路径缩略
	--       file_ignore_patterns = { 'node_modules','.git','target','dist' },
	--       vimgrep_arguments = {                        -- 让 rg 默认带 --hidden
	--         'rg','--color=never','--no-heading','--with-filename',
	--         '--line-number','--column','--smart-case','--hidden'
	--       },
	--       layout_config = { horizontal = { preview_width = 0.55 } },
	--       mappings = {
	--         i = {
	--           ['<C-j>'] = require('telescope.actions').move_selection_next,
	--           ['<C-k>'] = require('telescope.actions').move_selection_previous,
	--           ['<C-c>'] = require('telescope.actions').close,
	--         },
	--       },
	--     },
	--     pickers = {
	--       find_files = { find_command = { 'fdfind','--type','f','--hidden','--exclude','.git' } },
	--       live_grep  = { additional_args = { '--hidden' } },
	--     },
	--     extensions = {
	--       fzf = { fuzzy = true, override_generic_sorter = true, override_file_sorter = true },
	--     },
	--   }
	--   -- 按需加载扩展
	--   pcall(require('telescope').load_extension, 'fzf')
	-- end
}
