# 配置UTF-8 Locale环境变量
export LANG=en_US.utf8
export LC_ALL=en_US.utf8
export LC_CTYPE=en_US.utf8 # 可选：单独指定字符编码类型

alias ls="lsd --icon=always"
alias ll="lsd -l --icon=always" # 显示详细信息
alias la="lsd -a --icon=always" # 显示隐藏文件

if [[ $- == *i* ]] && [[ -z "$TMUX" ]] && [[ -z "$STY" ]];then
  tmux new-session -A -s main
fi

# PROMPT='%~ %#'
eval "$(starship init zsh)"

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Disabled Underline
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none

source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

